### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by jackbibby1** [jackbibby1/SCPA#6]
- [x]  Improve description of functions in ?
- [x] Add heat map visualisation
- [x] Add web page for visualisations
- [ ] Add feature selection method as in #11 
- [x] Add function to deal with SingleCellExperiment objects
- [x] Optimize memory usage in generating pathway matrices at in #17 
- [x] Allow assay specification in `seurat_extract()` and `compare_seurat()` as in #28 
- [ ] Parallel implementation of compare_pathways()

**Comment by jgarces02** [comment]
- [ ] Perform all calculations in sparse matrices (or hdf5) to avoid the computer collapsing because of RAM requirements.

**Comment by jackbibby1** [comment]
> * [ ]  Perform all calculations in sparse matrices (or hdf5) to avoid the computer collapsing because of RAM requirements.

I'll look at doing this when I get a minute. Can you let me know what you're running that means you don't have enough system RAM though? I assume this is mainly when you're using the `parallel = x` argument? FYI -- in case you're using a version of SCPA that's <1.3, upgrading should improve things a lot

**Comment by jgarces02** [comment]
I'm using version 1.5.4 and yes, with `parallel = T, cores = 5`... under an HPC environment, so I guess I shouldn't have problems with the RAM (but when monitoring the process with _htop_, all nodes are almost at 100%).

**Comment by tuhulab** [comment]
Producibility issue when cell number are larger than 500.

**Comment by jackbibby1** [comment]
Hi @tuhulab 

Sorry for the late reply. 

Appreciate the comments. This is a tough one because ideally, if the clustering is granular enough, downsampling the cells shouldn't have a large meaningful difference on the most differentially regulated pathways. And I think this is what you see, where the further down the ranked list you go, the more variable the rank is. It may be more insightful to show qval or pval here rather than rank as well, to show how stable the pvals are. 

Plus, I'm not sure what these populations are that you're comparing -- are these a particular cell type (i.e. naive T cells), or a bunch of different finer populations (i.e. T cells)?

Some rationale of why I'm hesitant to change things:

1) Permutation: I don't think the large increase in computational time will be worth the biological insight
2) Seed: I would hope the identified signatures would be robust enough to be prominent when comparing the same populations multiple times on a downsampled value. If this isn't the case, then a seed implementation would actually add error, and then I think the issue here is with cluster granularity or cell contamination (e.g. doublets) rather than downsampling.
3) There's an option to change the downsampling in the function, so people can already do this.

If people are very concerned with reproducibility, my recommendation would be to just run SCPA a few times and take the average qval output. Secondly, if you're getting wildly different results between SCPA runs, I'd argue that this is likely due to a lack of clustering resolution, or having contaminating cells in your cluster that are contributing to the variable output. 

Happy to hear more thoughts on this

Jack
